# Generated by Django 4.1.6 on 2023-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mascot', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
                ('wins_overall', models.IntegerField()),
                ('losses_overall', models.IntegerField()),
                ('wins_conf', models.IntegerField()),
                ('losses_conf', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
