# Generated by Django 4.1.6 on 2023-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
