# Generated by Django 4.1.6 on 2023-02-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='losses_conf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses_overall',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins_conf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins_overall',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins_overall', models.IntegerField()),
                ('losses_overall', models.IntegerField()),
                ('wins_conf', models.IntegerField()),
                ('losses_conf', models.IntegerField()),
                ('year', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
