# Generated by Django 4.1.6 on 2023-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_losses_conf_remove_team_losses_overall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ties_conf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='ties_overall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
