# Generated by Django 4.1.6 on 2023-02-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_record_ties_conf_record_ties_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
    ]
