# Generated by Django 4.1.6 on 2023-02-08 23:26

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='team_logos', validators=[teams.models.validate_svg]),
        ),
    ]
