# Generated by Django 4.1.6 on 2023-02-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
