# Generated by Django 4.1.6 on 2023-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_bsb_page_team_year_joined_team_year_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year_left',
            field=models.CharField(default='9999', max_length=50),
            preserve_default=False,
        ),
    ]
