# Generated by Django 4.1.6 on 2023-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='whip',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
