# Generated by Django 4.1.6 on 2023-02-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_batter_is_latest_fielder_is_latest_pitcher_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='year',
            field=models.CharField(default='2022', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fielder',
            name='year',
            field=models.CharField(default='2022', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitcher',
            name='year',
            field=models.CharField(default='2022', max_length=50),
            preserve_default=False,
        ),
    ]
