# Generated by Django 4.1.6 on 2023-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_batter_team_alter_fielder_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='team_games',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fielder',
            name='team_games',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitcher',
            name='team_games',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
